name = "MembraneElectrostatics"
uuid = "c2ac3933-6c5f-4d30-b17d-1f04dba38953"
authors = ["Jarvist Moore Frost <jarvist@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Gnuplot = "dc211083-a33a-5b79-959f-2ff34033469d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
LinearAlgebra = "1.11.0"
ProgressMeter = "1.10.2"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
